MyTontine/urls.py
from os import stat
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Tontine.urls')),
    path('user/',include('User.urls')),
]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Tontine/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('mes_tontine/<int:id>/', views.mes_tontine, name='mes_tontine'),
    path('mes_reunion/', views.mes_reunion, name='mes_reunion'),
    path('profile/<int:id>/', views.profile, name='profile'),
    path('creation_tontine/', views.create_tontine, name="create_tontine"),
    path('creation_reunion/', views.create_reunion, name="create_reunion"),
    path('tontine/<int:id>/', views.tontine, name='tontine'),
    path('tontines/', views.info_tontine, name='tontines'),
    path('reunions/', views.info_reunion, name='reunions'),
    path('creer_reunion/<int:idtontine>/',
         views.create_meeting, name='create_meeting'),
    path('creer_election/<int:idtontine>/',
         views.create_election, name='creer_election'),
    path('deposer_canidature/<int:idtontine>/', views.deposer_candidature,
         name='deposer_candidature'),
    path('confirmer_candidature/<int:idelection>/',
         views.confirmer_depos, name='confirmer_depos'),
    path('election/<int:idtontine>/',
         views.selection_election, name='select_election'),
    path('voter/<int:idelection>/', views.Voter, name="aller_voter"),
    path('confirmer_vote/', views.confirmer_vote, name='confirmer_vote'),
    path('confirmer_vote_president/<int:idelection>/',
         views.confirmer_vote_president, name="voter_president"),
    path('confirmer_vote_tresorier/<int:idelection>/',
         views.confirmer_vote_tresorier, name="voter_tresorier"),
    path('confirmer_vote_commisaire/<int:idelection>/',
         views.confirmer_vote_commisaire, name="voter_commisaire"),
    path('confirmer_vote_secreataire/<int:idelection>/',
         views.confirmer_vote_secreataire, name="voter_secretaire"),
    path('resultat_election/<int:idtontine>/',
         views.resultat_election, name='resultat_election'),
    path('demande_invitation/<int:idtontine>/',
         views.envoyer_unenotification, name="envoyer_unenotification"),
    path('notification/', views.recevoir_notification, name='mes_notification'),
    path('accepter_demande/', views.accepter_invitation, name='accepter_demande'),
    path('getNotification/', views.count_notif, name='getNotif'),
    path('modify_profile/', views.modifier_profile, name='modify_profile'),
    path('creation_fond/<int:idtontine>/',
         views.creer_fond, name='create_fond'),
    path('creer_cotisation/<int:idtontine>/',
         views.creer_cotisation, name="create_cotisation"),

]

User/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.login_user,name='login'),
    path('logout/',views.logout_user,name='logout'),
]

Tontine/models.py
import datetime
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.db import models

from django.contrib.auth.models import User

import uuid

from django.db.models.base import Model
from django.db.models.expressions import F, Func

# Create your models here.

# 3UPDATING THE USER FORMS


class MyUserManager(BaseUserManager):

    def create_user(self, username, surname, address, email, telephone, date_of_birth, profession, profile, password=None):
        if not username:
            raise ValueError("User muts have a user username")
        if not surname:
            raise ValueError("User muts have a user surname")
        if not address:
            raise ValueError("User muts have a user address")
        if not email:
            raise ValueError("User muts have a user email")
        if not telephone:
            raise ValueError("User muts have a user telephone")
        if not date_of_birth:
            raise ValueError("User muts have a user date of birth")
        if not profession:
            raise ValueError("User muts have a user profession")

        user = self.model(
            username=username,
            surname=surname,
            address=address,
            email=self.normalize_email(email),
            telephone=telephone,
            date_of_birth=date_of_birth,
            profession=profession,
            profile=profile
        )

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, username, surname, address, email, telephone, date_of_birth, profession, profile, password=None):

        user = self.create_user(
            username,
            surname,
            address,
            email,
            telephone,
            date_of_birth,
            profession,
            profile,
            password=password
        )

        user.is_admin = True
        user.save(using=self._db)

        return user


class MyUser(AbstractBaseUser):

    username = models.CharField(max_length=40)
    surname = models.CharField(max_length=40)
    address = models.CharField(max_length=40)
    email = models.EmailField(
        verbose_name='email  address', max_length=255, unique=True)
    telephone = models.CharField('Telephone Number', max_length=40)
    date_of_birth = models.DateField()
    profession = models.CharField(max_length=50)
    profile = models.ImageField(default="profile.png", null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = [
        'username',
        'surname',
        'address',
        'telephone',
        'date_of_birth',
        'profession',
        'profile'
    ]

    def __str__(self):
        return self.username + " "+self.surname

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def imageURL(self):
        try:
            img = self.profile.url
            #print("image ", img)
        except:
            img = ''

        return img

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


User = MyUser

# Table Tontine


class Tontine(models.Model):
    nom = models.CharField('Nom Tontine', max_length=255)
    date_creation = models.DateTimeField('Date De Creation', auto_now_add=True)
    #numero_de_membre = models.IntegerField('Nombre De Membre',default=1)
    slogan = models.CharField('Slogan', max_length=255)
    reglement_interieur = models.TextField('Réglement Intérieur')
    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.nom)

# Table TontineMembre


class MesTontine(models.Model):
    PRES = 'PR'  # president
    TRE = 'TR'  # tresorier
    SC = 'SC'  # secraitaire
    SCA = 'SCA'  # secretaire adjoint
    CAC = 'CAC'  # commissaire au compte
    CACA = 'CACA'  # commissaire au compte adjoint
    FONCTION = [
        (PRES, 'President'),
        (TRE, 'Tresorier'),
        (SC, 'Secretaire'),
        (SCA, 'Secretaire Adjoint'),
        (CAC, 'Commissaire aux Compte'),
        (CACA, 'Commissaire aux Compte Adjoint')
    ]
    id_tontine = models.ForeignKey(
        Tontine, on_delete=models.CASCADE, related_name='tontine')
    id_membre = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='membres')
    nombre_de_part = models.IntegerField('Nombre de part')
    fonction = models.CharField(max_length=30, choices=FONCTION, blank=True)
    date_integration = models.DateTimeField(default=datetime.datetime.now)

    def __str__(self):
        return 'Tontine : {} Membre : {}'.format(self.id_tontine, self.id_membre)


# TABLE ELECTION
class Election(models.Model):
    id = models.IntegerField(primary_key=True, unique=True, editable=False)
    date = models.DateField("Date De L'election")
    id_tontine = models.ForeignKey(Tontine, on_delete=models.CASCADE)
    terme = models.CharField("Terme Election", max_length=3000, blank=True)
    temp_renouvelable = models.CharField('Temp Renouvelable', max_length=200)
    creator = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    date_creation = models.DateTimeField(auto_now=True)
    date_fin_canditure = models.DateField()

    class Meta:
        ordering = ['date']

    def __str__(self):
        return 'Election {} Du {}'.format(self.id_tontine, self.date)

# Table Candidat


class Candidat(models.Model):
    PRES = 'President'  # president
    TRE = 'Tresorier'  # tresorier
    SC = 'Secretaire'  # secraitaire
    SCA = 'Secretaire Adjoint'  # secretaire adjoint
    CAC = 'Commissaire aux Compte'  # commissaire au compte
    CACA = 'Commissaire aux Compte Adjoint'  # commissaire au compte adjoint
    POST = [
        (PRES, 'President'),
        (TRE, 'Tresorier'),
        (SC, 'Secretaire'),
        (SCA, 'Secretaire Adjoint'),
        (CAC, 'Commissaire aux Compte'),
        (CACA, 'Commissaire aux Compte Adjoint')
    ]
    id_election = models.ForeignKey(
        Election, on_delete=models.CASCADE, related_name="election")
    id_user = models.ForeignKey(User, on_delete=models.CASCADE)
    poste_canidat = models.CharField(
        'Post Candidature', choices=POST, max_length=40)
    nombre_de_voix = models.IntegerField(default=0)
    # liste_participant = models.ManyToManyField(User,blank=True) #liste de ceux qui on voter

    class Meta:
        ordering = ['-nombre_de_voix']

    def __str__(self):
        return f'{self.id_user}'

# table cotisation


class Cotisation(models.Model):

    cycle_cotisation = (
        ('journalier', 'journalier'),
        ('Hebdomaider', 'Hebdomaider'),
        ('Menseule', 'Menseule'),
        ('Trimestriel', 'Trimestriel'),
        ('Semestriel', 'Semestriel'),
        ('Annuelle', 'Annuelle')
    )

    id = models.IntegerField(primary_key=True, unique=True, editable=False)
    id_tontine = models.ForeignKey(Tontine, on_delete=models.CASCADE)
    nom_cotisation = models.CharField('Nom', max_length=60)
    montant = models.FloatField('Montant Cotisation')
    date = models.DateField('Date de début')
    cycle = models.CharField(
        max_length=40, choices=cycle_cotisation, blank=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    nombre_participant = models.IntegerField(default=0)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    #paticipant = models.ManyToManyField(User, blank=True)

# table pret


class Pret(models.Model):
    id = models.IntegerField(primary_key=True, unique=True)
    id_tontine = models.ForeignKey(Tontine, models.CASCADE)
    nom_pret = models.CharField('Nom', max_length=255)
    date = models.DateField()
    member = models.ForeignKey(User, models.DO_NOTHING)
    montant = models.IntegerField()
    raison = models.CharField('Raison Du Pret', max_length=255)
    data_de_paiement_reel = models.DateField('Date de paiement réel')
    taux_interet = models.FloatField("Taux D'interet")
    taux_de_sanction = models.FloatField("Taux de sanction")


# table fond
class Fond(models.Model):
    id = models.IntegerField(primary_key=True, unique=True, editable=False)
    id_tontine = models.ForeignKey(Tontine, on_delete=models.CASCADE)
    type_fond = models.CharField('Type De Fond', max_length=30)
    nom = models.CharField('Nom', max_length=30)
    regles = models.CharField('Régles', max_length=255)
    montant_base = models.FloatField('Montant De Base')
    objectif = models.TextField("Objectif")

    def __str__(self):
        return f'Fond {self.nom} Tontine {self.id_tontine}'

# table reunion


class Reunion(models.Model):
    id = models.IntegerField(primary_key=True, unique=True, editable=False)
    id_tontine = models.ForeignKey(
        Tontine, on_delete=models.CASCADE)
    nom = models.CharField("Nom De Reunion", max_length=50)
    date = models.DateField('Date Reunion')
    lieu = models.CharField('Lieux Reunion', max_length=40)
    heure = models.TimeField('Heure Reunion')
    motif = models.TextField('Motif reunion', max_length=500)

    def __str__(self):
        return self.nom


class MesReunion(models.Model):
    PRES = 'PR'  # president
    TRE = 'TR'  # tresorier
    SC = 'SC'  # secraitaire
    SCA = 'SCA'  # secretaire adjoint

Tontine/forms.py
from typing import Any, Dict
from django.core import validators
from django.core.exceptions import ValidationError
from django.db.models import fields
from django.forms import ModelForm
from django.forms.widgets import SelectDateWidget
from .models import Tontine, Reunion, Candidat, Election, Fond, Cotisation
from django import forms
from django.db import models


class TontineCreationForm(ModelForm):

    reglement_interieur = forms.Textarea()

    class Meta:
        model = Tontine
        fields = ['nom', 'slogan', 'reglement_interieur']

    widgets = {
        'nom': forms.TextInput(attrs={'class': 'form-control'}),
        'slogan': forms.TextInput(attrs={'class': 'form-control'}),
        'reglement_interieur': forms.TextInput(attrs={'class': 'form-control'}),
    }

    def clean_field(self):
        data = self.cleaned_data.get("reglement_interieur")

        if len(data) == 1:
            raise ValidationError("Reglement Interieur Non Valide")

        return data


class ReunionCreationForm(ModelForm):

    class Meta:
        model = Reunion
        fields = '__all__'
        #fields = ['tontine', 'nom', 'date', 'motif', 'lieu', 'heure']


class CreateReunion(ModelForm):

    class Meta:
        model = Reunion
        fields = ['nom', 'date', 'motif', 'lieu', 'heure']


class CreateElection(ModelForm):
    terme = forms.CharField(
        max_length=3000, help_text='  Veillez entrez un bon terme svp!')

    class Meta:
        model = Election
        fields = ['date', 'terme', 'temp_renouvelable', 'date_fin_canditure']

    def clean(self):
        cleaned_data = super().clean()
        data = cleaned_data.get("date")
        data1 = cleaned_data.get("date_fin_canditure")

        print(type(data), type(data1))

        if data1 > data:
            msg = [
                'La date de fin de candidature doit etre inferieur a la date de election!']
            raise ValidationError(msg)

    def save(self, commit: bool = False):
        elect = super().save(commit=commit)
        if commit:
            elect.save()
        return elect

    # def cleaned_date_fin_candidature(self):
    #     date = self.cleaned_data.get('date_fin_candidature')
    #     date1 = self.cleaned_data.get("temp_renouvelable")
    #     if date > date1:
    #         raise ValidationError(
    #             "La Date De Fin de Candidature doit etre inferieur a la date de l'ection!")

    #     return date


class DeposerCandidature(ModelForm):

    PRES = 'President'  # president
    TRE = 'Tresorier'  # tresorier
    SC = 'Secretaire'  # secraitaire
    CAC = 'Commissaire aux Compte'  # commissaire au compte

    choice = [
        (PRES, PRES),
        (TRE, TRE),
        (SC, SC),
        (CAC, CAC)
    ]

    poste_canidat = forms.ChoiceField(
        choices=choice, help_text='Selectionner le poste au qu\'elle vous soliciter ')

    class Meta:
        model = Candidat
        fields = ['poste_canidat']


class CreateFond(ModelForm):

    class Meta:
        model = Fond
        fields = ['type_fond', 'nom', 'regles', 'montant_base', 'objectif']


class CreateCotisation(ModelForm):

    class Meta:
        model = Cotisation
        fields = '__all__'
        exclude = ['id_tontine', 'nombre_participant', 'creator', 'cycle']

Tontine/templates/tontine/base.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/w3.css' %}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">
    <title>Nv Tontine</title>

    <style>
        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .form-control-dark {
            color: #fff;
            background-color: var(--bs-dark);
            border-color: var(--bs-gray);
        }

        .form-control-dark:focus {
            color: #fff;
            background-color: var(--bs-dark);
            border-color: #fff;
            box-shadow: 0 0 0 .25rem rgba(255, 255, 255, .25);
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .text-small {
            font-size: 85%;
        }

        .dropdown-toggle {
            outline: 0;
        }

        @media screen and (max-width:480px) {

            h5,
            h1,
            h2,
            h3,
            h4 {
                font-size: 1rem;
            }
        }
    </style>
</head>

<body>
    {% include 'tontine/navbar.html' %}
    </script>
    <section id='contents'>
        <div class="container">
            {% block content %}{% if messages %} {% for message in messages %}
            <!-- <div class="alert alert-{{message.tags}}" role="alert">
                {{message}}
            </div> -->
            <div class="alert alert-{{message.tags}} d-flex align-items-center" role="alert">
                <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:">
                    <use xlink:href="#check-circle-fill" />
                </svg>
                <div>
                    {{message}}
                </div>
            </div>

            {% endfor %} {% endif %} {% endblock %}
        </div>
    </section>
    <script src="{% static 'assets/vendors/glightbox/js/glightbox.min.js' %}"></script>
    <!-- <script src="{% static 'js/my.js' %}"></script>-->

    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/mcstudios/glightbox/dist/js/glightbox.min.js"></script>


    <script>
        $(document).ready(function () {
            setInterval(
                function () {
                    $.ajax({
                        type: 'GET',
                        url: '/getNotification/',
                        success: function (response) {
                            console.log(response.message);
                            $("#msg").text(response.msg)
                        },
                        error: function (response) {

                        }
                    });
                }, 1000
            );
        })
    </script>
</body>

</html>

Tontine/templates/tontine/choisir_candidat.html
{% extends 'tontine/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <br>
    <br>
    <br />
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th,
        td {
            text-align: left;
            padding: 8px;
            text-align: center;
            border: 1px solid #ddd;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2
        }

        th {
            background-color: #4CAF50;
            color: white;
        }
    </style>
    {{query}}
    {{xxx}}
    {{q}}
    {% if candidat %}
    <div style="overflow-x: auto;margin:0;padding:0">
        <table>
            <tr>
                <th>
                    Nom
                </th>
                <th>
                    Poste
                </th>
                <th style="text-align: center;">Nombre de Voix</th>
                <th>Voter</th>
            </tr>

            {% for cand in cand_elec %}
            <tr>
                <td title="affichier le profile du candidat">
                    {% if cand.candidat.id_user == request.user %}
                    <a href="{% url 'profile' cand.candidat.id_user.id %}">Vous</a>
                    {% else %}
                    <a href="{% url 'profile' cand.candidat.id_user.id %}">{{cand.candidat.id_user|truncatechars:10}}</>
                        {% endif %}
                </td>
                <td>
                    {{cand.candidat.poste_canidat}}
                </td>
                <td style="text-align: center;">
                    {{cand.candidat.nombre_de_voix}}
                </td>
                <td>
                    {% if cand.hasvote %}
                    <label class="text-danger">Vous avez deja voter</label>
                    {% else %}
                    <a href="/confirmer_vote/?idelection={{election.id}}&idcandidat={{cand.candidat.id}}"
                        class="btn btn-success form-control">Vote</a>
                    {% endif %}
                </td>
            </tr>
            <div class="collapse card">
                <div class="card-header">
                    <p>hell</p>
                </div>
                <div class="card-body">
                    <p>
                        Hello world
                    </p>
                </div>
            </div>
            {% endfor %}
        </table>
    </div>
    <br />
    <div class="w3-container">

        {% for item in cand_elec %}
        <div class="w3-card w3-display-container" style="width:100%">
            <img src="{{item.candidat.id_user.profile.url}}" alt="Person" style="width:100%">
            <div class="w3-container">
                <h4><b>{{item.candidat.id_user}}</b></h4>
                <h4><b>Poste</b> : {{item.candidat.poste_canidat}}</h4>
                <h4><b>Nombre de voix : </b>{{item.candidat.nombre_de_voix}}</h4>
                <div class="w3-container" style="padding:20px">
                    {% if item.hasvote %}
                    <label class="text-danger">Vous avez deja voter</label>
                    {% else %}
                    <a href="/confirmer_vote/?idelection={{election.id}}&idcandidat={{cand.candidat.id}}"
                        class="btn btn-success form-control">Voter</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    {% else %}
    <h1>Desoler Aucun Candidat</h1>
    {% endif %}
</div>

{% endblock %}

Tontine/templates/tontine/create_candidature.html
{% extends 'tontine/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <br>
    <br>
    <br />
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th,
        td {
            text-align: left;
            padding: 8px;
            border: 1px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2
        }

        th {
            background-color: #4CAF50;
            color: white;
        }

        @media screen and (max-width:480px) {

            th,
            td,
            h5 {
                font-size: 10pt;
            }
        }
    </style>
    {% if election %}
    <h1>Deposer Une Canidature</h1>
    <h5>a l'association <b>{{tontine}}</b></h5>

    <div style="overflow-x: auto;">
        <table>
            <tr>
                <th>
                    Date
                </th>
                <th>
                    Terme
                </th>
                <th>
                    Temp Renouvelable
                </th>
                <th>

                </th>
            </tr>
            {% for item in elect %}
            <tr>
                <td>
                    {{item.elections.date}}
                </td>
                <td>
                    {{item.elections.terme}}
                </td>
                <td>
                    {{item.elections.temp_renouvelable}}
                </td>
                <td>
                    {% if item.isCandidat %}
                    <h5 class="text-danger">Vous avez deja deposer votre candidature</h5>
                    {% else %}
                    <a href="{% url 'confirmer_depos' item.elections.id %}" class="btn btn-success">Deposer
                        Canidature</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>

    </form>
    {% else %}
    <h1>Desoler ! aucun election n'as ete lancer !</h1>
    {% endif %}
</div>

{% endblock %}

Tontine/templates/tontine/create_cotisation.html
{% extends 'tontine/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="container">
    <br>
    <br>
    <br />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <h1 style="font-size: 2em;">Creer Une Reunion Pour L'association {{name.nom}}</h1>
    <form method="POST">
        {% csrf_token %}
        <input type="hidden" name="idtontine" value="idtontine">
        {% for value in form %}

        {% if value.label == 'Date de début' %}
        <p>Date de début<input type="date" name="date" required id="id_date"></p>
        {% elif value.label == 'Montant Cotisation' %}
        <p>Montant Cotisation<input type="number" name="montant" min="0" step="any" required id="id_montant"></p>
        {% else %}
        <p>{{value.label}}{{value}}</p>
        {% endif %}
        {% endfor %}
        <br />
        <center>
            <input type="submit" value="Creer Reunion" style="width: 96%;">

        </center>
        <!-- <script>
            $("input", "textarea").addClass("form-control");
        </script> -->
    </form>
</div>

{% endblock %}

Tontine/templates/tontine/create_reunion.html
{% extends 'tontine/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <br>
    <br>
    <br />
    <h1>Creer Une Reunion</h1>
    <h5>Appartenant a la tontine</h5>
    <form method="POST">
        {% csrf_token %} {{form|crispy}}
        <br />
        <button class="btn btn-secondary" type="submit">Creer Tontine</button>
        <!-- <script>
            $("input", "textarea").addClass("form-control");
        </script> -->
    </form>
</div>

{% endblock %}

Tontine/templates/tontine/creer_fond.html
{% extends 'tontine/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<br />
<br />
<br />
<div>
    <style>
        .errorlist {
            color: red;
        }

        .errorlist>li {
            color: red;
        }

        input[type=number] {
            width: 99%;
            box-sizing: border-box;
            border: 2px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
            margin-left: 4px;
            margin-right: 10px;
            background-color: white;
            padding: 12px 20px 12px 10px;
            -webkit-transition: width 0.4s ease-in-out;
            transition: width 0.4s ease-in-out;
        }
    </style>
    <center>
        <h3>Creer Un Fond</h3>
    </center>
    <form method="post">
        {% csrf_token %}
        {{form}}
        <br>
        <br>
        <center><input type="submit" value="Modify" style="width:100%"></center>
    </form>
</div>
{% endblock %}

Tontine/templates/tontine/depose_candidature.html
{% extends 'tontine/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <br>
    <br>
    <br />
    <h1>Confirmer Une Candidature</h1>
    <h2>Pour {{election}}</h2>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert">
        {{message}}
    </div>
    {% endfor %}
    {% endif %}
    <form method="POST">
        {% csrf_token %}

        {{form|crispy}}<br />
        <button class="btn btn-secondary" type="submit">Confirmer</button>
        <!-- <script>
            $("input", "textarea").addClass("form-control");
        </script> -->
    </form>
</div>

{% endblock %}

Tontine/templates/tontine/info_reunion.html
{% extends 'tontine/base.html' %} {% block content %}
<br />
<br />
<br />
<br />
<section id="reunion" style="padding: 30px;">
    <div class="container">
        <h1>List Reunion</h1>
    </div>
    {% for reunion in reunions %}
    <div class="accordion" id="accordionExample">
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne"
                    aria-expanded="true" aria-controls="collapseOne">
                    {{reunion}}
                </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne"
                data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <strong>Date Reunion : </strong>{{reunion.date}}<br>
                    <strong>Motif : </strong>{{reunion.motif}}<br />
                </div>
            </div>
        </div>
    </div>
    <br>
    {% endfor %}


</section>
{% endblock %}