MyTontine/urls.py
from os import stat
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Tontine.urls')),
    path('user/',include('User.urls')),
]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.login_user,name='login'),
    path('logout/',views.logout_user,name='logout'),
]

Tontine/models.py
import datetime
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.db import models

from django.contrib.auth.models import User

import uuid

from django.db.models.base import Model
from django.db.models.expressions import F, Func

# Create your models here.

# 3UPDATING THE USER FORMS


class MyUserManager(BaseUserManager):

    def create_user(self, username, surname, address, email, telephone, date_of_birth, profession, profile, password=None):
        if not username:
            raise ValueError("User muts have a user username")
        if not surname:
            raise ValueError("User muts have a user surname")
        if not address:
            raise ValueError("User muts have a user address")
        if not email:
            raise ValueError("User muts have a user email")
        if not telephone:
            raise ValueError("User muts have a user telephone")
        if not date_of_birth:
            raise ValueError("User muts have a user date of birth")
        if not profession:
            raise ValueError("User muts have a user profession")

        user = self.model(
            username=username,
            surname=surname,
            address=address,
            email=self.normalize_email(email),
            telephone=telephone,
            date_of_birth=date_of_birth,
            profession=profession,
            profile=profile
        )

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, username, surname, address, email, telephone, date_of_birth, profession, profile, password=None):

        user = self.create_user(
            username,
            surname,
            address,
            email,
            telephone,
            date_of_birth,
            profession,
            profile,
            password=password
        )

        user.is_admin = True
        user.save(using=self._db)

        return user


class MyUser(AbstractBaseUser):

    username = models.CharField(max_length=40)
    surname = models.CharField(max_length=40)
    address = models.CharField(max_length=40)
    email = models.EmailField(
        verbose_name='email  address', max_length=255, unique=True)
    telephone = models.CharField('Telephone Number', max_length=40)
    date_of_birth = models.DateField()
    profession = models.CharField(max_length=50)
    profile = models.ImageField(default="profile.png", null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = [
        'username',
        'surname',
        'address',
        'telephone',
        'date_of_birth',
        'profession',
        'profile'
    ]

    def __str__(self):
        return self.username + " "+self.surname

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def imageURL(self):
        try:
            img = self.profile.url
            #print("image ", img)
        except:
            img = ''

        return img

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


User = MyUser

# Table Tontine


class Tontine(models.Model):
    nom = models.CharField('Nom Tontine', max_length=255)
    date_creation = models.DateTimeField('Date De Creation', auto_now_add=True)
    #numero_de_membre = models.IntegerField('Nombre De Membre',default=1)
    slogan = models.CharField('Slogan', max_length=255)
    reglement_interieur = models.TextField('Réglement Intérieur')
    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.nom)

# Table TontineMembre


class MesTontine(models.Model):
    PRES = 'PR'  # president
    TRE = 'TR'  # tresorier
    SC = 'SC'  # secraitaire
    SCA = 'SCA'  # secretaire adjoint
    CAC = 'CAC'  # commissaire au compte
    CACA = 'CACA'  # commissaire au compte adjoint
    FONCTION = [
        (PRES, 'President'),
        (TRE, 'Tresorier'),
        (SC, 'Secretaire'),
        (SCA, 'Secretaire Adjoint'),
        (CAC, 'Commissaire aux Compte'),
        (CACA, 'Commissaire aux Compte Adjoint')
    ]
    id_tontine = models.ForeignKey(
        Tontine, on_delete=models.CASCADE, related_name='tontine')
    id_membre = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='membres')
    nombre_de_part = models.IntegerField('Nombre de part')
    fonction = models.CharField(max_length=30, choices=FONCTION, blank=True)
    date_integration = models.DateTimeField(default=datetime.datetime.now)

    def __str__(self):
        return 'Tontine : {} Membre : {}'.format(self.id_tontine, self.id_membre)


# TABLE ELECTION
class Election(models.Model):
    id = models.IntegerField(primary_key=True, unique=True, editable=False)
    date = models.DateField("Date De L'election")
    id_tontine = models.ForeignKey(Tontine, on_delete=models.CASCADE)
    terme = models.CharField("Terme Election", max_length=3000, blank=True)
    temp_renouvelable = models.CharField('Temp Renouvelable', max_length=200)
    creator = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    date_creation = models.DateTimeField(auto_now=True)
    date_fin_canditure = models.DateField()

    class Meta:
        ordering = ['date']

    def __str__(self):
        return 'Election {} Du {}'.format(self.id_tontine, self.date)

# Table Candidat


class Candidat(models.Model):
    PRES = 'President'  # president
    TRE = 'Tresorier'  # tresorier
    SC = 'Secretaire'  # secraitaire
    SCA = 'Secretaire Adjoint'  # secretaire adjoint
    CAC = 'Commissaire aux Compte'  # commissaire au compte
    CACA = 'Commissaire aux Compte Adjoint'  # commissaire au compte adjoint
    POST = [
        (PRES, 'President'),
        (TRE, 'Tresorier'),
        (SC, 'Secretaire'),
        (SCA, 'Secretaire Adjoint'),
        (CAC, 'Commissaire aux Compte'),
        (CACA, 'Commissaire aux Compte Adjoint')
    ]
    id_election = models.ForeignKey(
        Election, on_delete=models.CASCADE, related_name="election")
    id_user = models.ForeignKey(User, on_delete=models.CASCADE)
    poste_canidat = models.CharField(
        'Post Candidature', choices=POST, max_length=40)
    nombre_de_voix = models.IntegerField(default=0)
    # liste_participant = models.ManyToManyField(User,blank=True) #liste de ceux qui on voter

    class Meta:
        ordering = ['-nombre_de_voix']

    def __str__(self):
        return f'{self.id_user}'

# table cotisation


class Cotisation(models.Model):

    cycle_cotisation = (
        ('journalier', 'journalier'),
        ('Hebdomaider', 'Hebdomaider'),
        ('Menseule', 'Menseule'),
        ('Trimestriel', 'Trimestriel'),
        ('Semestriel', 'Semestriel'),
        ('Annuelle', 'Annuelle')
    )

    id = models.IntegerField(primary_key=True, unique=True, editable=False)
    id_tontine = models.ForeignKey(Tontine, on_delete=models.CASCADE)
    nom_cotisation = models.CharField('Nom', max_length=60)
    montant = models.FloatField('Montant Cotisation')
    date = models.DateField('Date de début')
    cycle = models.CharField(
        max_length=40, choices=cycle_cotisation, blank=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    nombre_participant = models.IntegerField(default=0)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    #paticipant = models.ManyToManyField(User, blank=True)

# table pret


class Pret(models.Model):
    id = models.IntegerField(primary_key=True, unique=True)
    id_tontine = models.ForeignKey(Tontine, models.CASCADE)
    nom_pret = models.CharField('Nom', max_length=255)
    date = models.DateField()
    member = models.ForeignKey(User, models.DO_NOTHING)
    montant = models.IntegerField()
    raison = models.CharField('Raison Du Pret', max_length=255)
    data_de_paiement_reel = models.DateField('Date de paiement réel')
    taux_interet = models.FloatField("Taux D'interet")
    taux_de_sanction = models.FloatField("Taux de sanction")


# table fond
class Fond(models.Model):
    id = models.IntegerField(primary_key=True, unique=True, editable=False)
    id_tontine = models.ForeignKey(Tontine, on_delete=models.CASCADE)
    type_fond = models.CharField('Type De Fond', max_length=30)
    nom = models.CharField('Nom', max_length=30)
    regles = models.CharField('Régles', max_length=255)
    montant_base = models.FloatField('Montant De Base')
    objectif = models.TextField("Objectif")

    def __str__(self):
        return f'Fond {self.nom} Tontine {self.id_tontine}'

# table reunion


class Reunion(models.Model):
    id = models.IntegerField(primary_key=True, unique=True, editable=False)
    id_tontine = models.ForeignKey(
        Tontine, on_delete=models.CASCADE)
    nom = models.CharField("Nom De Reunion", max_length=50)
    date = models.DateField('Date Reunion')
    lieu = models.CharField('Lieux Reunion', max_length=40)
    heure = models.TimeField('Heure Reunion')
    motif = models.TextField('Motif reunion', max_length=500)

    def __str__(self):
        return self.nom


class MesReunion(models.Model):
    PRES = 'PR'  # president
    TRE = 'TR'  # tresorier
    SC = 'SC'  # secraitaire
    SCA = 'SCA'  # secretaire adjoint

User/models.py
from django.db import models

# Create your models here.

User/forms.py
from django.db import models
from django.db.models import fields
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.forms.widgets import SelectDateWidget
from Tontine.admin import UserCreationForm
from django import forms


'''class DateSelectorWidget(forms.MultiWidget):
    def __init__(self, attrs=None):
        days = [(day, day) for day in range(1, 32)]
        months = [(month, month) for month in range(1, 13)]
        years = [(year, year) for year in [2018, 2019, 2020]]
        widgets = [
            forms.Select(attrs=attrs, choices=days),
            forms.Select(attrs=attrs, choices=months),
            forms.Select(attrs=attrs, choices=years),
        ]
        super().__init__(widgets, attrs)

    def decompress(self, value):
        if isinstance(value, date):
            return [value.day, value.month, value.year]
        elif isinstance(value, str):
            year, month, day = value.split('-')
            return [day, month, year]
        return [None, None, None]

    def value_from_datadict(self, data, files, name):
        day, month, year = super().value_from_datadict(data, files, name)
        # DateField expects a single string that it can parse into a date.
        return '{}-{}-{}'.format(year, month, day)

'''


class FormUser(ModelForm):

    class Meta:
        model = UserCreationForm
        #fields = '__all__'
        fields = ['username', 'surname', 'address', 'email', 'telephone',
                  'date_of_birth', 'profession', 'password', 'password1']
        # fields = ['username','first_name','last_name','email','password','password1']

User/views.py
from django.shortcuts import render, redirect
# Create your views here.
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from time import strftime
#from django.contrib.auth.forms import UserCreationForm

from Tontine.admin import UserCreationForm


def login_user(request):
    template = 'usertemplate/login.html'
    context = {}

    context['year'] = strftime("%Y")

    if request.method == 'POST':
        username = request.POST['email']
        password = request.POST['password']
        _user = authenticate(request, username=username, password=password)

        if _user is not None:
            login(request, _user)
            print('login sucessfully')
            return redirect('home')
        else:
            messages.success(
                request, ("There Was an error with authentication"))
            return redirect('login')

    return render(request, template, context)


def register(request):
    template = 'usertemplate/register.html'
    context = {}

    if request.method == 'POST':
        form = UserCreationForm(request.POST or None)
        if form.is_valid():
            form.save()
            email = form.cleaned_data['email']
            password = form.cleaned_data['password1']
            _user = authenticate(request, username=email, password=password)
            login(request, _user)
            return redirect('home')
        else:
            messages.success(
                request, ("There Was an error with authentication"))
            return redirect('register')
    form = UserCreationForm

    context['form'] = form

    return render(request, template, context)


def logout_user(request):
    logout(request)
    return redirect('home')

User/templates/usertemplate/login.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">

    <link rel="stylesheet" href="{% static 'boot/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css" />
    <script src="https://cdn.jsdelivr.net/gh/mcstudios/glightbox/dist/js/glightbox.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">
    <title>Nv Tontine | Login</title>
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        html,
        body {
            height: 100%;
        }

        body {
            display: flex;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }

        .form-signin .checkbox {
            font-weight: 400;
        }

        .form-signin .form-floating:focus-within {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }

        div img {
            margin-left: auto;
            margin-right: auto;
            display: block;
        }
    </style>
</head>

<body>
    <br>
    <br>
    <br> {% if messages %} {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>Sorry</strong> {{message}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %} {% endif %}
    <div class="container">
        <main class="form-signin">

            <form method="POST">
                {% csrf_token %}

                <div>
                    <img class="mb-4" src="{% static 'logo/logo.png' %}" alt="logo" width="200" height="150">

                </div>

                <h4 class="h3 mb-3 fw-normal">Please sign into your Nv Account</h4>

                <div class="form-floating">
                    <input type="email" name="email" class="form-control" id="floatingInput"
                        placeholder="name@example.com">
                    <label for="floatingInput">Email address</label>
                </div>
                <br />
                <div class="form-floating">
                    <input type="password" name="password" class="form-control" id="floatingPassword"
                        placeholder="Password">
                    <label for="floatingPassword">Password</label>
                </div>

                <div class="checkbox mb-3">
                    <!-- <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label> -->
                </div>
                <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
                <div>
                    <small id="emailHelp" class="form-text text-muted">Create An Account <a
                            href="{% url 'register' %}">Create An Account</a></small><br />

                </div>
                <p class="mt-5 mb-3 text-muted" style="text-align: center;">&copy; 2021–{{year}}</p>
            </form>
        </main>
    </div>
    <script src="{% static 'assets/vendors/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>


<!-- <div class="container shadow form-signin" style="padding:20px;margin:auto;">
    {% if messages %} {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>Sorry</strong> {{message}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
    </div>
    {% endfor %} {% endif %}
    <h1>Login to your account</h1>
    <form method="POST" class="form-control">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleInputEmail1">Email Address </label>
            <input type="text" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" name="password" class="form-control" id="exampleInputPassword1">
        </div>
        <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div> 
<small id="emailHelp" class="form-text text-muted">Create An Account <a href="{% url 'register' %}">Create An Account</a></small><br/>
<br/>
<button type="submit" class="btn btn-primary">Submit</button>
</form>
</div> -->

User/templates/usertemplate/register.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="image" href="{% static 'logo/logo.png' %}" type="image/png">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css" />
    <script src="https://cdn.jsdelivr.net/gh/mcstudios/glightbox/dist/js/glightbox.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">
    <title>Nv Tontine | Register</title>
    <style>
        input[type=text],
        input[type=password],
        input[type=file],
        input[type=date],
        input[type=email] {
            width: 99%;
            box-sizing: border-box;
            border: 2px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
            margin-left: 4px;
            margin-right: 10px;
            background-color: white;
            padding: 12px 20px 12px 10px;
            -webkit-transition: width 0.4s ease-in-out;
            transition: width 0.4s ease-in-out;
        }

        input[type=text]:focus {
            border: 3px solid rgba(6, 201, 226, 0.795);
        }

        label {
            padding-left: 4px;
        }

        input[type=submit],
        button {
            background-color: #4CAF50;
            color: white;
            padding: 12px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        input[type=submit]:hover {
            background-color: #45a049;
        }

        .container {
            width: 90%;
            padding: 5px 5px 5px 5px;
            display: block;
            justify-content: center;
        }

        @media screen and (min-width:480px) {
            .container {
                width: 50%;
                padding: 5px 5px 5px 5px;
                display: block;
            }

            input {

                margin-right: 10px;
            }
        }
    </style>

</head>

<body>
    <br>
    <br>
    {% if messages%} {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{message}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %} {% endif %}
    <div class="shadow container">
        <main class="form-signin">
            <br />
            <div>
                <img style="display:block;margin-left:auto;margin-right:auto" class="mb-4"
                    src="{% static 'logo/logo.png' %}" alt="logo" width="200" height="150">

            </div>
            <h2 style="text-align: center;">Register To Nv Tontine</h2><br />
            <form method="POST" class="form-floating ">
                {% csrf_token %}
                {% for t in form%}
                {% if t.label == 'Date of birth' %}
                <p><label>{{t.label}}</label>
                    <input type="date" name="date_of_birth" required id="id_date_of_birth">
                </p>
                </p>
                {% else %}
                <p><label>{{t.label}}</label>
                    {{t}}</p>
                {% endif %}
                {% endfor %}
                <small class="form-text text-muted">Already Have an account.<a
                        href="{% url 'login' %}">login</a></small>
                <br />
                <b />
                <input type="submit" value="Register">
                <!-- <button type="submit" class=""></button> -->
                <br />
            </form>
            <br>
            <p style="text-align: center;">Copyright<i class="fas fa-copyright"></i>2022</p>
            <br />
        </main>
    </div>
    <br>
    <br>

    <br>
    <script src="{% static 'assets/vendors/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script>
        $('input').addClass("form-control");
    </script>
</body>

</html>